SELECT
    a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES)
FROM
    BOOK_SALES s
JOIN
    BOOK b USING (BOOK_ID)
JOIN 
    AUTHOR a USING (AUTHOR_ID)
WHERE
    s.SALES_DATE LIKE '2022-01%'
GROUP BY
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY
ORDER BY
    a.AUTHOR_ID ASC,
    b.CATEGORY DESC
