SELECT
    t1.PRODUCT_CODE,
    t1.PRICE * SUM(t2.SALES_AMOUNT) AS SALES
FROM
    PRODUCT t1
JOIN
    OFFLINE_SALE t2
ON
    t1.PRODUCT_ID = t2.PRODUCT_ID
GROUP BY
    t1.PRODUCT_CODE, t1.PRICE
ORDER BY
    SALES DESC,
    t1.PRODUCT_CODE;