SELECT
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    u.GENDER AS GENDER,
    COUNT(DISTINCT u.USER_ID) AS USERS
FROM
    ONLINE_SALE o
JOIN
    USER_INFO u USING (USER_ID)
WHERE
    u.GENDER IS NOT NULL
GROUP BY
    YEAR,
    MONTH,
    GENDER
ORDER BY
    YEAR,
    MONTH,
    GENDER

