SELECT 
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    COUNT(DISTINCT u.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT u.USER_ID) / (SELECT COUNT(*) FROM USER_INFO u2 WHERE YEAR(u2.JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO u
JOIN ONLINE_SALE o USING (USER_ID)
WHERE YEAR(u.JOINED) = 2021
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)