SELECT 
    DISTINCT CAR_ID, 
    IF(t.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY c
LEFT JOIN (
    SELECT
        CAR_ID 
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
) AS t USING (CAR_ID)
ORDER BY
    CAR_ID DESC