SELECT
    r.HISTORY_ID,
    FLOOR(MIN(
    ((DATEDIFF(r.END_DATE, r.START_DATE) + 1) * c.DAILY_FEE)
        * (100 - COALESCE(CAST(SUBSTRING_INDEX(d.DISCOUNT_RATE, '%', 1) AS SIGNED), 0)) / 100)) AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY r
JOIN
    CAR_RENTAL_COMPANY_CAR c USING (CAR_ID)
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
    ON
        c.CAR_TYPE = d.CAR_TYPE
        AND DATEDIFF(r.END_DATE, r.START_DATE) >= CAST(SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS SIGNED)
WHERE
    c.CAR_TYPE = '트럭'
GROUP BY
    HISTORY_ID
ORDER BY
    FEE DESC,
    r.HISTORY_ID DESC