SELECT 
    r.HISTORY_ID,
    FLOOR(
        (DATEDIFF(r.END_DATE, r.START_DATE) + 1) * c.DAILY_FEE *
        (100 - COALESCE(MAX(CAST(SUBSTRING_INDEX(d.DISCOUNT_RATE, '%', 1) AS SIGNED)), 0)) / 100
    ) AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY r
JOIN
    CAR_RENTAL_COMPANY_CAR c ON 
        c.CAR_ID = r.CAR_ID AND 
        c.CAR_TYPE = '트럭'
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON
        d.CAR_TYPE = '트럭' AND
        DATEDIFF(r.END_DATE, r.START_DATE) + 1 >= CAST(SUBSTRING_INDEX(d.DURATION_TYPE, '일', 1) AS SIGNED)
GROUP BY
    r.HISTORY_ID
ORDER BY
    FEE DESC,
    r.HISTORY_ID DESC;