SELECT
    FLAVOR
FROM
    FIRST_HALF f
JOIN (
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM
        JULY
    GROUP BY
        FLAVOR
) AS j USING(FLAVOR)
ORDER BY
    (f.TOTAL_ORDER + j.TOTAL_ORDER) DESC
LIMIT
    3