SELECT
    m.MEMBER_NAME,
    r.REVIEW_TEXT,
    DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    REST_REVIEW r
JOIN
    MEMBER_PROFILE m USING (MEMBER_ID)
JOIN (
    SELECT
        MEMBER_ID
    FROM
        REST_REVIEW
    GROUP BY
        MEMBER_ID
    ORDER BY
        COUNT(*) DESC
    LIMIT
        1
) t USING (MEMBER_ID)
ORDER BY
    REVIEW_DATE ASC,
    REVIEW_TEXT ASC