SELECT
    MONTH(START_DATE) AS MONTH,
    c.CAR_ID AS CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY c
JOIN (
    SELECT
        CAR_ID, COUNT(*) AS TOTAL_RECORDS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE >= '2022-08-01'
        AND START_DATE < '2022-11-01'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5
) AS t USING (CAR_ID)
WHERE
    c.START_DATE >= '2022-08-01'
    AND c.START_DATE < '2022-11-01'
GROUP BY
    CAR_ID,
    MONTH
HAVING
    RECORDS > 0
ORDER BY
    MONTH ASC,
    CAR_ID DESC