SELECT t2.TOTAL_SCORE AS SCORE, t1.EMP_NO, t1.EMP_NAME, t1.POSITION, t1.EMAIL
FROM HR_EMPLOYEES t1
JOIN (
    SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO 
    ORDER BY TOTAL_SCORE DESC
    LIMIT 1
) t2 ON t1.EMP_NO = t2.EMP_NO;