SELECT
    CONCAT(
        CONCAT(CONCAT('/home/grep/src/', b.BOARD_ID), '/'),
        CONCAT(CONCAT(f.FILE_ID, f.FILE_NAME), f.FILE_EXT)
    ) AS FILE_PATH
FROM
    USED_GOODS_FILE f
JOIN
    (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) b USING (BOARD_ID)
ORDER BY
    f.FILE_ID DESC