SELECT f.CATEGORY, f.PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN (SELECT CATEGORY, MAX(PRICE) AS PRICE
      FROM FOOD_PRODUCT 
      GROUP BY CATEGORY 
      HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
     ) d
ON f.CATEGORY = d.CATEGORY AND f.PRICE = d.PRICE
ORDER BY f.PRICE DESC