SELECT
    t1.BOOK_ID,
    t2.AUTHOR_NAME,
    DATE_FORMAT(t1.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM
    BOOK t1
JOIN
    AUTHOR t2
USING
    (AUTHOR_ID)
WHERE
    t1.CATEGORY = '경제'
ORDER BY
    t1.PUBLISHED_DATE